-- DEPRECATED: RSP recruitment tables are now created by init-schema.sql.
--
-- Fresh installs — run only:
--   psql -d hrms_plaridel -f scripts/init-schema.sql
--
-- After init, apply attachment storage policy (required for RSP file uploads):
--   psql -d hrms_plaridel -f scripts/rsp-storage-attachment-policy.sql
--
-- Existing databases that were created before this merge can still use the
-- one-off migrations under scripts/migrate-*.sql if a column is missing.
