-- DEPRECATED (L&D tables): L&D and RSP saved-form tables are now created by init-schema.sql.
--
-- Fresh installs — run only:
--   psql -d hrms_plaridel -f scripts/init-schema.sql
--
-- Existing databases that were created before this merge can still use the
-- one-off migrations under scripts/migrate-*.sql if a column is missing.
--
-- DocuTracker tables are NOT in init-schema.sql. Use:
--   psql -d hrms_plaridel -f scripts/init-schema-docutracker.sql
